# Generated by Django 5.2.7 on 2026-02-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdCatalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Nivel Seguridad',
                'verbose_name_plural': 'Niveles de Seguridad',
            },
        ),
    ]
