"""
Django settings for sgdSource project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dnnh#5cl067zfoc^d)7$r(@27)zn^pacb!*l5grv_0wo+-v^b4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'instrCooperacion',
    'sgdDocumentos',
    'sgdCatalogo',
    'sgdConocimiento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sgdSource.urls'

UNFOLD = {
    "SITE_SUBHEADER": "Administración",
    "SITE_TITLE": "MIDENA SGD",
    "SITE_HEADER": "MIDENA SGD",
    "COLORS": {
       
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",   # 👈 color principal (azul actual)
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110"
        },
        },

    "SIDEBAR": {
        "navigation": [
            {
                 "title": "Gestión Documental",
    "icon": "diamond",
    "collapsible": True,
    "permission": lambda request: (
        request.user.has_perm("sgdConocimiento.view_sgdconocimiento")
        or request.user.has_perm("instrCooperacion.view_instrcooperacion")
    ),
    "items": [
        {
            "title": "Gestión del Conocimiento",
            "link": "/admin/sgdConocimiento/sgdconocimiento/",
            "permission": lambda request: request.user.has_perm(
                "sgdConocimiento.view_sgdconocimiento"
            ),
        },
        {
            "title": "Instrumentos de Cooperación",
            "link": "/admin/instrCooperacion/instrumentocooperacion/",
            "permission": lambda request: request.user.has_perm(
                "instrCooperacion.view_instrumentocooperacion"
            ),
        },
    ],
            },
            {
                "title": "Administración",
                "icon": "users",
                "collapsible": True,
                "permission": lambda request: (
        request.user.has_perm("auth.view_user")
        or request.user.has_perm("auth.view_group")
    ),
                "items": [
                    {
                        "title": "Usuarios",
                        "link": "/admin/auth/user/",
                        "permission": lambda request: request.user.has_perm(
                "auth.view_user"
            ),
                    },
                    {
                        "title": "Grupos",
                        "link": "/admin/auth/group/",
                        "permission": lambda request: request.user.has_perm(
                "auth.view_group"
            ),
                    },
                ],
            },
            {
                "title": "Configuración",
                "icon": "folder",
                "collapsible": True,
                  "permission": lambda request: (
        request.user.has_perm("sgdCatalogo.view_knowledgedocumenttype")
        or request.user.has_perm("sgdCatalogo.view_potentialapplication")
    ),
                "items": [
                    {
                        "title": "Tipos documentales",
                        "link": "/admin/sgdCatalogo/knowledgedocumenttype/",
                        "permission": lambda request: request.user.has_perm(
                            "sgdCatalogo.view_knowledgedocumenttype"
                        ),
                    },
                     {
                        "title": "Aplicaciones potenciales",
                        "link": "/admin/sgdCatalogo/aplicacionpotencial/",
                        "permission": lambda request: request.user.has_perm(
                            "sgdCatalogo.view_aplicacionpotencial"
                        ),
                    },
                    
                ],
            }
        ],
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'sgdSource.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sgd-test-midena',
        'USER': 'postgres',
        'PASSWORD': 'diego',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
#STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

#STATIC_ROOT = str(BASE_DIR / "staticfiles")