# Generated by Django 5.2.7 on 2026-02-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sgdCatalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgdConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='sgdConocimiento/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aplicacion_potencial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conocimientos', to='sgdCatalogo.aplicacionpotencial')),
                ('red_investigacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conocimientos', to='sgdCatalogo.redesinvestigacion')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conocimientos', to='sgdCatalogo.referencia')),
            ],
            options={
                'verbose_name': 'Conocimiento',
                'verbose_name_plural': 'Gestión de Conocimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
