# Generated by Django 5.2.7 on 2026-01-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sgdDocumentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('publication_date', models.DateField()),
                ('issn', models.CharField(blank=True, max_length=50)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sgdDocumentos.document')),
            ],
        ),
    ]
