# Generated by Django 6.0.1 on 2026-02-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoCooperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Código de Instrumento')),
                ('ambito_de_cooperacion', models.CharField(choices=[('I+D+i', 'I+D+i'), ('estudio', 'Estudio'), ('transferencia', 'Transferencia del conocimiento'), ('intercambio', 'Intercambio de productos y servicios'), ('formacion', 'Formación'), ('comercializacion', 'Comercialización'), ('cofabricacion', 'Cofabricación')], max_length=50, verbose_name='Ámbito de Cooperación')),
                ('objeto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Objeto')),
                ('alcance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alcance')),
                ('productos_entregables', models.CharField(blank=True, max_length=255, null=True, verbose_name='Productos Entregables')),
                ('impacto_institucional', models.CharField(blank=True, max_length=255, null=True, verbose_name='Impacto Institucional')),
                ('compromisos_de_las_partes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compromisos de las Partes')),
                ('logros_alcanzados', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logros Alcanzados')),
                ('fecha_suscripcion', models.DateField(verbose_name='Fecha de Suscripción')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='instrCooperacion/', verbose_name='Documento PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Instrumento de Cooperación',
                'verbose_name_plural': 'Instrumentos de Cooperación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
